services:
  polybot:
    image: ${IMG_NAME}
    restart: always
    ports:
      - "8000:8000"
    env_file: .env
    networks:
      - observability

    healthcheck:
      test: ["CMD-SHELL", "wget --spider --quiet http://localhost:8000 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s


  otelcol:
    image: otel/opentelemetry-collector-contrib:latest
    restart: always
    command: ["--config", "/etc/otelcol/config.yaml"]
    ports:
      - "8889:8889"
    volumes:
      - ./otelcol-config.yaml:/etc/otelcol/config.yaml
    networks:
      - observability
    depends_on:
      polybot:
        condition: service_healthy

networks:
  observability:
