version: '3.9'
services:
  polybot:
    image: ${IMG_NAME}
    restart: always
    ports:
      - "8000:8000"
    env_file: .env
    networks:
      - observability

  otelcol:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config", "/etc/otelcol/config.yaml"]
    ports:
      - "8889:8889"
    volumes:
      - ./otelcol-config.yaml:/etc/otelcol/config.yaml
    networks:
      - observability

networks:
  observability:
