receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: 'polybot'
          static_configs:
            - targets: ['polybot:8000']  # container name + internal port

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"

service:
  pipelines:
    metrics:
      receivers: [prometheus]
      exporters: [prometheus]
