name: Deploy Polybot

on:
  push:
    branches:
      - main

jobs:
  deploy-polybot:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    env:
      PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
      EC2_IP: ${{ secrets.POLYBOT_EC2_IP }}
      REPO: ${{ github.repository }}
    steps:
      - name: Set up SSH key
        run: |
          echo "$PRIVATE_KEY" > key.pem
          chmod 600 key.pem

      - name: SSH and deploy
        run: |
          ssh -i key.pem -o StrictHostKeyChecking=no ubuntu@$EC2_IP << 'EOF'
            REPO_DIR="PolybotServicePython"
            if [ -d "$REPO_DIR" ]; then
              echo "Directory $REPO_DIR exists. Pulling latest changes..."
              cd "$REPO_DIR"
              git pull
            else
              echo "Cloning repository into $REPO_DIR..."
              git clone https://github.com/${REPO}.git "$REPO_DIR"
              cd "$REPO_DIR"
            fi

            echo "Installing and restarting polybot service..."
            sudo cp polybot.service /etc/systemd/system/polybot.service

            if [ ! -d "venv" ]; then
              echo "Creating Python virtual environment..."
              python3 -m venv venv
            fi

            source venv/bin/activate
            pip install -r polybot/requirements.txt

            sudo systemctl daemon-reload
            sudo systemctl restart polybot.service
          
            
            echo "[+] Setting up OpenTelemetry Collector"

            if ! command -v otelcol &> /dev/null; then
              echo "📦 Installing otelcol..."
              curl -LO https://github.com/open-telemetry/opentelemetry-collector-releases/releases/download/v0.97.0/otelcol_0.97.0_linux_amd64.deb
              sudo dpkg -i otelcol_0.97.0_linux_amd64.deb
            else
              echo "✅ otelcol already installed."
            fi

            echo "⚙️ Updating OpenTelemetry config if needed"
            if ! cmp -s otelcol-config.yaml /etc/otelcol/config.yaml; then
              sudo cp otelcol-config.yaml /etc/otelcol/config.yaml
              sudo systemctl restart otelcol
              sleep 5
            else
              echo "✅ Config already up to date"
            fi

            sudo systemctl enable otelcol

            echo "🔍 Verifying metrics endpoint..."
            if curl -s http://localhost:8889/metrics | grep -q 'system_cpu_time'; then
              echo "✅ OpenTelemetry metrics are exposed"
            else
              echo "⚠️ Metrics not available"
              sudo systemctl status otelcol --no-pager
            fi
          
          EOF
