name: Test and Deploy Polybot

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  TestImgProcessingChatbotApp:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r polybot/requirements.txt

      - name: Test filters
        run: |
          echo -e "\n\nTesting concat()\n"
          python -m polybot.test.test_concat

          echo -e "\n\nTesting rotate()\n"
          python -m polybot.test.test_rotate

          echo -e "\n\nTesting salt_n_pepper()\n"
          python -m polybot.test.test_salt_n_pepper

          echo -e "\n\nTesting segment()\n"
          python -m polybot.test.test_segment

      - name: Test Telegram bot logic
        run: |
          python -m polybot.test.test_telegram_bot

      - name: Deploy to EC2
        if: github.ref == 'refs/heads/main' && success()
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          EC2_IP: ${{ secrets.POLYBOT_EC2_IP }}
        run: |
          echo "$PRIVATE_KEY" > key.pem
          chmod 600 key.pem
          ssh -i key.pem -o StrictHostKeyChecking=no ubuntu@$EC2_IP '
            if [ ! -d "polybot" ]; then
              echo "Cloning polybot repository..."
              git clone https://github.com/${{ github.repository }}.git polybot
            fi
      
            cd polybot
            git pull
      
            echo "Installing and restarting polybot service..."
            sudo cp deploy/polybot.service /etc/systemd/system/polybot.service
            sudo systemctl daemon-reload
            sudo systemctl restart polybot.service
          '

