name: Docker Scout Scan

on:
  pull_request:
    branches:
      - main

jobs:
  scout:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          IMAGE_TAG=polybot:${{ github.sha }}
          docker build -t $IMAGE_TAG .
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Run Docker Scout vulnerability scan
        uses: docker/scout-action@v1
        with:
          command: cves
          image: ${{ env.IMAGE_TAG }}
          exit-code: true
          format: json
          summary: true
          write-comment: true
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate SBOM
        run: |
          docker scout sbom ${{ env.IMAGE_TAG }} > scout_sbom.json

      - name: Upload SBOM as artifact
        uses: actions/upload-artifact@v4
        with:
          name: scout-sbom
          path: scout_sbom.json
