name: Docker Scout Scan

on:
  pull_request:
    branches:
      - main

jobs:
  scout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Scout CLI
        run: |
          curl -sSfL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh | sh -s --

      - name: Build Docker image
        run: |
          IMAGE_TAG=polybot:${{ github.sha }}
          docker build -t $IMAGE_TAG .

      - name: Run Docker Scout for high/critical CVEs
        run: |
          docker scout cves $IMAGE_TAG --severities high,critical --exit-code


      - name: Generate SBOM
        if: always()
        run: |
          docker scout sbom polybot:${{ github.sha }} > scout_sbom.json

      - name: Upload SBOM as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: scout-sbom
          path: scout_sbom.json

